### REST Data HTTP service
server.port=8090
server.servlet.context-path=/DSA-SQL-JDBCService/rest

### JDBC Data Source
# URL-ul se formeaza asa: jdbc:postgresql://[server]:[port]/[nume_baza_de_date]?currentSchema=[nume_schema]
jdbc.data.source.DB_URL=jdbc:postgresql://localhost:5432/project-SII?currentSchema=movies_pg

jdbc.data.source.USER=postgres
jdbc.data.source.PASS=postgres

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=debug

# SpringBoot Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=developer
spring.security.user.password=iis
